backend:
  name: Nekorra/HOUMAN-HOMAYOUN-WEBSITE
  branch: main # Branch to update (optional; defaults to master)
media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "Data" # Used in routes, e.g., /admin/collections/blog
    label: "Data" # Used in the UI
    folder: "data" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
  - name: "Pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
