# This is a basic workflow to help you get started with Actions

name: Build Public folder

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: build
        - run: hugo
        - run: cd public
      -name: push to new repo
        - run: |
          git init
          git config --global user.email 'abhisrin@gmail.com'
          git config --global user.password "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"
          git add .
          git commit -m "public push"
          git remote add origin https://github.com/Nekorra/HOUMAN-HOMAYOUN-WEBSITE-BUILD.git
          git push -u origin main